### ISSUE TITLE
测试运行时出错

### ISSUE THREAD

**Issue by CB-Jason** [zsrl/pywencai#14]
本人属小白，看到这个项目在测试时出现以下错误
C:\Users\ASUS\Scripts\python.exe D:/A股相关/test.py 
Traceback (most recent call last):
  File "D:\A股相关\test.py", line 2, in <module>
    res = pywencai.get(query='退市股票', sort_key='退市@退市日期', sort_order='asc')
  File "C:\Users\ASUS\lib\site-packages\pywencai\wencai.py", line 68, in get
    return getPage(**kwargs)
  File "C:\Users\ASUS\lib\site-packages\pywencai\wencai.py", line 32, in getPage
    list = result['data']['answer'][0]['txt'][0]['content']['components'][0]['data']['datas']
KeyError: 'data'
电脑已经安装了Node.js

**Comment by zsrl** [comment]
![image](https://github.com/zsrl/pywencai/assets/4284926/8896333f-7339-4e38-a30b-f16962900561)
未复现问题

**Comment by CB-Jason** [comment]
邮件已收到，我会尽快回复，谢谢！
