### ISSUE TITLE
请问我的程序什么总是报错啊?

### ISSUE THREAD

**Issue by weisong5908** [zsrl/pywencai#20]
Traceback (most recent call last):
  File "stock_wordpress_all.py", line 98, in <module>
    stock_post_creator.create_post()
  File "stock_wordpress_all.py", line 60, in create_post
    res_stock = pywencai.get(query=f"{self.today_wc_q} 涨停股票 剔除ST *ST股票")
  File "C:\Program Files\python\lib\site-packages\pywencai\wencai.py", line 182, in get
    data = params.get('data')
AttributeError: 'NoneType' object has no attribute 'get'

我 self.today_wc_q 这个数字就是当天的日期  例如20XX-XX-XX的格式。

**Comment by zsrl** [comment]
升级最新版，安装jsdom依赖，具体参看文档
