### ISSUE TITLE
Get的时候报错

### ISSUE THREAD

**Issue by Lwan12** [zsrl/pywencai#26]
已经更新到了最新版本
报错如下:
/usr/local/lib/python3.8/site-packages/pywencai/hexin-v.bundle.js:102785
      this[filesSymbol] ||= FileList.createImpl(this._globalObject);
                        ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
/usr/local/lib/python3.8/site-packages/pywencai/hexin-v.bundle.js:102785
      this[filesSymbol] ||= FileList.createImpl(this._globalObject);

**Comment by zsrl** [comment]
Node.js需要v16+
