### ISSUE TITLE
空指针，有排查具体问题的方法么？IP问题？

### ISSUE THREAD

**Issue by super13** [zsrl/pywencai#31]
res = pywencai.get(query='多方炮')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.11/site-packages/pywencai/wencai.py", line 182, in get
    data = params.get('data')
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by spytensor** [comment]
我以为是我的网络有问题，是不是接口改了

**Comment by super13** [comment]
目测ip被封禁，连直接去网页抓之后curl都有问题，现在正常了，估计时效过了。
