### ISSUE TITLE
pywencai无法获取数据

### ISSUE THREAD

**Issue by justin745** [zsrl/pywencai#47]
一直以来可以正确使用pywencai，但突然发现无法获取数据了。比如pywencai在pypi.org的范例如下：
```
import pywencai

res = pywencai.get(query='退市股票', sort_key='退市@退市日期', sort_order='asc')
print(res)
```

运行后出错：
```
Traceback (most recent call last):
  File "/Users/usr/git/div_invest/venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3548, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-93879abb35df>", line 3, in <module>
    res = pywencai.get(query='退市股票', sort_key='退市@退市日期', sort_order='asc')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usr/git/div_invest/venv/lib/python3.11/site-packages/pywencai/wencai.py", line 185, in get
    data = params.get('data')
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by justin745** [comment]
重新安装了Node.js，问题解决了。
