### ISSUE TITLE
这个问题再次出现AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by xujianjun99** [zsrl/pywencai#51]
大佬求助，这个问题再次出现！
环境:
Python 3.8.10
windows 11
pywencai 0.12.2

python test.py
Traceback (most recent call last):
File "D:/TEST/test.py", line 2, in 
res = pywencai.get(query='退市股票', sort_key='退市@退市日期', sort_order='asc')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:/python38/Lib/site-packages/pywencai/wencai.py", line 185, in get
data = params.get('data')
^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by montrush** [comment]
好像是问财的api接口挂了，不知道是不是永久性的关闭

**Comment by zjlhcnlay** [comment]
接口挂了,等待作者更新吧

**Comment by umie0128** [comment]
+1 接口嘎了没人维护

**Comment by cloudchina** [comment]
通过在wencai.py和headers.py中加try调试，如下
![image](https://github.com/user-attachments/assets/0e8b1831-8da9-477d-ba62-451402f2d3c5)
![image](https://github.com/user-attachments/assets/491b7641-363a-457f-a675-f851dea46d97)
最终输出结果为
![image](https://github.com/user-attachments/assets/1210098a-35c3-42c5-9306-814be6fefb58)
可知是hexin-v.bundle.js获取token失败，猜测应该是账号密码过期了？

**Comment by cloudchina** [comment]
如果要爬取的话，可以临时使用
`def my_get_stock():
    user_agent = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/91.0.4472.124 Safari/537.36"}
    cookie = {"cookie": web_cookie}
    url = r"https://www.iwencai.com/customized/chart/get-robot-data"
    json_data = {
        "source": "Ths_iwencai_Xuangu", "version": "2.0", "query_area": "", "block_list": "",
        "add_info": "{\"urp\":{\"scene\":1,\"company\":1,\"business\":1},\"contentType\":\"json\",\"searchInfo\":true}",
        "question": "涨停", "perpage": 100, "page": 1, "secondary_intent": "stock",
        "log_info": "{\"input_type\":\"typewrite\"}", "rsh": "Ths_iwencai_Xuangu_sli22927woxbm9a2ol1o21tm0uvqn48d"
    }

    response = requests.post(url, json=json_data, cookies=cookie, headers=user_agent)
    data = response.json()
    all_stocks = data['data']['answer'][0]['txt'][0]['content']['components'][0]['data']['datas']
    for i in range(len(all_stocks)):
        print(all_stocks[i]['code'])


my_get_stock()`

其中web_cookie就是需要打开网站去找一下，按照readme里面的获取cookie方法，question后面的“涨停”字样也是需要替换为你自己的问题
