### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by allujrt** [zsrl/pywencai#55]
执行你的demo会报错：
Traceback (most recent call last):
  File "C:\Users\allujrt\PycharmProjects\wencai\src\wencai\demo.py", line 3, in <module>
    res = pywencai.get(query='退市股票', sort_key='退市@退市日期', sort_order='asc')
  File "C:\Users\allujrt\PycharmProjects\wencai\venv\lib\site-packages\pywencai\wencai.py", line 185, in get
    data = params.get('data')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by roby3721** [comment]
同样问题

**Comment by xiao2752271456** [comment]
服务器做了反爬，nginx forbidden。坐等解决办法吧
